language: python
sudo: required
dist: trusty
python:
 - 2.6
 - 2.7
env:
 - CASACORE=20
 - CASACORE=21
matrix:
 include:
  # TODO: https://github.com/casacore/python-casacore/issues/54
  #- os: osx
  #  language: generic
  #  env: CASACORE=21
  #  python: 3.5
  - os: linux
    language: python
    env: CASACORE=21
    python: 3.4
  # TODO: https://github.com/casacore/python-casacore/issues/59
  #- os: linux
  #  language: python
  #  env: CASACORE=21
  #  python: 3.5

before_install:
 - .travis/before_install.sh
install:
 - python setup.py develop
 - pip install -r tests/requirements.txt
 - pip install coveralls travis-sphinx
script:
 - nosetests --with-coverage
 - travis-sphinx --nowarn -s doc build
deploy:
 provider: pypi
 user: gijzelaerr
 password:
  secure: cdrrma3XaFjtv4lHvag6dfhSbKBF8iLmVgPQEjXP8qa+WxHnkHObkyraYAFGqThDY/0lBdrBm7Og6l1JfAcSA2BjdPQYxujP8KEoVicPwlgwEJ5LZo4HqympWVk33APvbcYNw7K/CwEXNJCCD1tDiO4pdwkPAWuKlnYUVfZq2yI=
 on:
  tags: true
  repo: casacore/python-casacore
after_success:
  coveralls
notifications:
  webhooks:
   urls:
    - https://webhooks.gitter.im/e/08a570c12a3afa37d8e2

