language: python
os: linux
dist: xenial
jobs:
  include:
  - env: TARGET=py2_casacore_v3.2
  - env: TARGET=py3_casacore_v3.2
  - env: TARGET=py2_casacore_master
  - env: TARGET=py3_casacore_master
  - env: TARGET=py2-kern
  - env: TARGET=py3-kern
  - env: TARGET=pep8
  - env: TARGET=mypy
  allow_failures:
  - env: TARGET=py2-kern
  - env: TARGET=py3-kern
  - env: TARGET=pep8
  - env: TARGET=mypy
services:
 - docker
before_install:
 - .travis/before_install.sh
install:
 - .travis/install.sh
script:
 - .travis/script.sh
deploy:
 provider: pypi
 username: gijzelaerr
 password:
  secure: cdrrma3XaFjtv4lHvag6dfhSbKBF8iLmVgPQEjXP8qa+WxHnkHObkyraYAFGqThDY/0lBdrBm7Og6l1JfAcSA2BjdPQYxujP8KEoVicPwlgwEJ5LZo4HqympWVk33APvbcYNw7K/CwEXNJCCD1tDiO4pdwkPAWuKlnYUVfZq2yI=
 skip_existing: true
 on:
  tags: true
  repo: casacore/python-casacore
after_success:
  coveralls
notifications:
  webhooks:
   urls:
    - https://webhooks.gitter.im/e/08a570c12a3afa37d8e2
